name: CI Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  clang-format-and-tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies for clang-format and clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format clang-tidy

      - name: Check code format and lint
        run: |
          make check-format-and-lint

  run-tests:
    runs-on: ubuntu-latest
    needs: clang-format-and-tidy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: actions/setup-cmake@v3
        with:
          cmake-version: '3.22.0'

      - name: Run tests
        run: |
          make run-tests

  generate-doc:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: actions/setup-cmake@v3
        with:
          cmake-version: '3.22.0'

      - name: Install dependencies for documentation
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Generate Documentation
        run: |
          make generate-doc

      - name: Commit and push documentation
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add docs/
          git commit -m 'Add generated documentation'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
