name: CI Workflow

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
# clang-format-and-tidy:
#   runs-on: ubuntu-latest
#   steps:
#     - name: Checkout code
#       uses: actions/checkout@v3
#
#     - name: Install dependencies for clang-format and clang-tidy
#       run: |
#         sudo apt-get update
#         sudo apt-get install -y clang-format clang-tidy
#
#     - name: Check code format and lint
#       run: |
#         make check-format-and-lint

  run-tests:
    runs-on: ubuntu-latest
#    needs: clang-format-and-tidy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: sudo apt-get install lcov gcovr

      - name: Run tests
        run: |
          make run-tests

      - name: Generate coverage report
        run: |
          make coverage-report

      - name: Commit updated coverage report
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add tests/
          git commit --amend --no-edit
          git push origin ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
