name: CI Workflow

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  clang-format-and-tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies for clang-format and clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format clang-tidy 

      - name: Install dependencies for OpenGL
        run: |
          sudo apt-get install -y libglew-dev libgl1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libglfw3-dev
      
      - name: Install dependencies for Qt
        run: |
          sudo apt-get install -y qt6-base-dev

      - name: Check code format and lint
        run: |
          make format-and-lint

  run-tests:
    runs-on: ubuntu-latest
    needs: clang-format-and-tidy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies for tests
        run: |
          sudo apt-get update
          sudo apt-get install -y libglew-dev libgl1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libglfw3-dev


      - name: Run tests
        run: |
          make configure-tests
          make run-tests