name: CI Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  clang-format-and-tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies for clang-format and clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format clang-tidy

      - name: Check code format and lint
        run: |
          make check-format-and-lint

  run-tests:
    runs-on: ubuntu-latest
    needs: clang-format-and-tidy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Run tests
        run: |
          make run-tests
